# 选填：工作流名称，也就是这个构建的名称。
# 如果不填，Github会将其设置为相对于存储库根目录的工作流文件路径
name: First example
# 必填：触发工作流程，也就是我们何时触发workflow的条件
on:
  push:
    branches:
      - master
jobs:
  hello-actions:
    runs-on: ubuntu-18.04
    name: hello-actions
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1

      - name: Cat text
        run: |
          cat text